In [1]:
import torch
print(torch.__version__)

1.11.0+cu113


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])

In [6]:
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.ndim

2

In [14]:
matrix.shape

torch.Size([2, 2])

## Create Random Tensor

In [16]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.4777, 0.4591, 0.0474, 0.8815],
         [0.6977, 0.8374, 0.2590, 0.8218],
         [0.7587, 0.7540, 0.0331, 0.6845]]), torch.float32)

In [18]:
random_image_tensor = torch.rand(size = (224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Create zero tensor

In [19]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [20]:
ones = torch.ones(size = (3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32)

In [21]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [25]:
float_16_tensor = torch.tensor([3, 4, 6],
                               dtype=torch.float16,
                               device='cpu',
                              )
float_16_tensor

tensor([3., 4., 6.], dtype=torch.float16)

In [28]:
some_tensor = torch.rand(size=(3, 4))
some_tensor
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

torch.Size([3, 4])
torch.float32
cpu


## Basic Ops

In [32]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor * 10

tensor([10, 20, 30])

In [34]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [35]:
tensor * tensor

tensor([1, 4, 9])

In [36]:
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
tensor @ tensor

tensor(14)

In [38]:
tensor_A = torch.rand(size = (3, 2))
tensor_B = torch.rand(size = (3, 2))
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [40]:
output = torch.matmul(tensor_A, tensor_B.T)
output, output.shape

(tensor([[0.6307, 0.3355, 0.7006],
         [0.7586, 0.4512, 0.8579],
         [0.5004, 0.3247, 0.5746]]), torch.Size([3, 3]))

In [41]:
torch.mm(tensor_A, tensor_B.T)

tensor([[0.6307, 0.3355, 0.7006],
        [0.7586, 0.4512, 0.8579],
        [0.5004, 0.3247, 0.5746]])

In [49]:
import torch
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2,
                         out_features=6)

x = tensor_A
output=linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 1.0442,  0.5700,  0.4291,  0.1711,  0.2328,  0.2888],
        [ 1.1087,  0.3854,  0.3489, -0.0267,  0.5447,  0.4684],
        [ 0.8856,  0.1269,  0.2903, -0.1956,  0.7585,  0.4256]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [53]:
x = torch.arange(10, 100, 10, dtype=torch.float32)
x

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [54]:
print(x.min())
print(x.max())
print(x.sum())
print(x.type(torch.float32).mean())
print(x.mean())

tensor(10.)
tensor(90.)
tensor(450.)
tensor(50.)
tensor(50.)


In [56]:
print(x.argmax())
print(x.argmin())

tensor(8)
tensor(0)


In [58]:
x.dtype

torch.float32

In [61]:
x_float16 = x.type(torch.float16)
x_float16.dtype

torch.float16

In [60]:
x_int8 = x.type(torch.int8)
x_int8.dtype

torch.int8

In [62]:
x = torch.arange(1., 8.)

In [66]:
x_reshaped = torch.reshape(x, (1, 7))
x_reshaped = x.reshape(1, 7)
x_reshaped, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([7]))

In [67]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [68]:
z[:, 0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [69]:
x_stacked = torch.stack([x, x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [70]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [71]:
x_unsqueeze = x_squeezed.unsqueeze(dim=0)
x_unsqueeze, x_unsqueeze.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [1]:
x_original = torch.rand(224, 224, 3)

x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape, x_original.shape

NameError: ignored

In [3]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [9]:
x[:, 2]

tensor([[7, 8, 9]])

In [10]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [13]:
x[0, 0, :]

tensor([1, 2, 3])

In [16]:
random_seed = 42
torch.manual_seed(seed=42)

tensor_A = torch.rand(size=(3, 4))

torch.random.manual_seed(seed = random_seed)
tensor_B = torch.rand(3, 4)

tensor_A == tensor_B


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])